### ISSUE TITLE
Prevent pushing node_modules to remote branch

### ISSUE THREAD

**Issue by adityaprakash-bobby** [TomasRoj/WhatsTheMeaning#1]
Define a `.gitignore` file to not stage unnecessary files into the version control and avoid pushing large files like in `node_modules` to the repository. :smiley:

**Comment by TomasRoj** [comment]
Hey,

I added that .gitignore for node_modules and other. Thanks for your idea!
-Tom

**Comment by adityaprakash-bobby** [comment]
That's great. You can go ahead and remove the `node_modules` folder from the master branch of this repository.

**Comment by TomasRoj** [comment]
Removing it shows me error that it can't find the libraries

**Comment by adityaprakash-bobby** [comment]
Remove the `node_modules` from git version control. You don't need to remove locally from your system. You can just not push it to the remote directory. This will do the job.
```bash
git rm -r node_modules/
```
You can follow [this link](https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository).

**Comment by TomasRoj** [comment]
ok finished, thanks
