### ISSUE TITLE
Missing package.json file

### ISSUE THREAD

**Issue by cernyfilip** [TomasRoj/WhatsTheMeaning#3]
I can see only package-lock.json file. Please add your package.json so it can be run locally.

**Comment by TomasRoj** [comment]
Thanks! Someone told me the same but it wasnt created autumatically so I added manually by npm init. Is it ok now?

**Comment by cernyfilip** [comment]
Yes, I can see it now.

**Comment by TomasRoj** [comment]
Please see the main bug issue what I am trying to fix now. Thats the prority.
